package:
  name: dquality
  version: '0.0.1'

source:
  git_url: https://github.com/ravescovi/data-quality.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - h5py
    - dxchange
 
  run:
    - dxchange
    - python
    - numpy
    - h5py
    
test:
  # Python imports
  imports:
    - dquality

about:
  home: http://project.readthedocs.org
  license: BSD-3
  summary: 'Add docs to any project.'
