
QUALITYERROR_LOW = -1
QUALITYERROR_HIGH = -2
NO_ERROR = 0

FILE_TYPE_HDF = 'FILE_TYPE_HDF'
FILE_TYPE_GE = 'FILE_TYPE_GE'

REPORT_NONE = 'none'
REPORT_ERRORS = 'errors'
REPORT_FULL = 'full'

FEEDBACK_CONSOLE = 'console'
FEEDBACK_LOG = 'log'
FEEDBACK_PV = 'pv'
FEEDBACK_PV_12 = 'pv_12'
FEEDBACK_FULL = 'full'

DATA_STATUS_DATA = 0
DATA_STATUS_MISSING = 1
DATA_STATUS_END = 2

ZMQ_CONTROLLER_PORT = 5511